apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jn95i9nxb-python
  janus-idp.io/tekton: jn95i9nxb-python
  backstage.io/kubernetes-id: jn95i9nxb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jn95i9nxb-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
